name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        
    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        # Informa à ação onde encontrar o package-lock.json para o cache
        cache-dependency-path: frontend/package-lock.json

    - name: Install Dependencies
      # Define o diretório de trabalho para este e os próximos passos
      working-directory: ./frontend
      run: npm ci

    - name: Build Project
      working-directory: ./frontend
      run: npm run build --if-present
